#pragma once

/*!
Game is implemented as a state machine with events -
this is a set of available events.
*/
enum GAME_EVENT
{
	GE_NULL,

	GE_FRAME_ENDED,

	GE_GAME_STARTED,

	GE_GAME_LOGO_FINISHED,
	GE_SPLASH_SCREEN_FINISHED,

	GE_SOUND_ON,
	GE_SOUND_OFF,

	GE_LEVEL_REQUESTED,
	GE_SOUND_MENU_REQUESTED,
	GE_HELP_REQUESTED,
	GE_ABOUT_REQUESTED,
	GE_EXIT_REQUESTED,

	GE_LEVEL_ABORTED,
	GE_LEVEL_SUCCEEDED,
	GE_LEVEL_FAILED,

	GE_LEVEL_CONTINUATION_REQUESTED,
	GE_MAIN_MENU_REQUESTED,

	GE_HELP_SCREEN_FINISHED,
	GE_ABOUT_SCREEN_FINISHED,

	GE_SUCCESS_SCREEN_FINISHED,
	GE_FAILURE_SCREEN_FINISHED,

	GE_GAME_FINISHED,

	GE_ADDITIONAL_RENDER_STARTING,
	GE_ADDITIONAL_RENDER_FINISHED,
};
